-- in Feb 13, 2013:
/*********************************************************************************************************/
SELECT *
  INTO [_bk_forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value_2013_02_13]
  FROM     [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
/*********************************************************************************************************/
-- Update
--     Display all country for 2010 as 1

UPDATE
           [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
SET
           [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value].[Display]
       =   1
WHERE      Field_fk	 = 28
  AND      Sex_fk    =  0
  AND      Age_fk    =  0
  
/*********************************************************************************************************/
-- Update
--     code "Display" for all data except for 2010 as 0
UPDATE
           [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
SET
           [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value].[Display]
       =   0
WHERE      Field_fk	 != 28
  
/*********************************************************************************************************/

-- in Feb 19, 2013:
/*********************************************************************************************************/
SELECT *
  INTO   [_bk_forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value_2013_02_19]
  FROM       [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
/*********************************************************************************************************/
-- Update
--     Display for 2010 as follows:
/*********************************************************************************************************/
--     For most rows of 2010 "Display" should be also coded as 0

UPDATE
             [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
SET
             [Display]
         =   0
WHERE      Field_fk	 = 28
  AND      Sex_fk   !=  0
  AND      Age_fk   !=  0


--     But for some rows of 2010 "Display" should be coded as 1

UPDATE
             [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
SET
             [Display]
         =   1
WHERE      Field_fk	 = 28
  AND      Sex_fk   !=  0
  AND      Age_fk   !=  0
  AND
     (
         ( Nation_fk =    2 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =    2 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =    6 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =    6 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =    9 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =    9 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   10 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   11 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   11 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   11 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   12 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =   13 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   14 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   15 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   15 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   15 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   16 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   16 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   16 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   16 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   17 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   17 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   19 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   19 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   20 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   20 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   20 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   21 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   21 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   21 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   22 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   22 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   22 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   22 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   25 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   25 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   26 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   26 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   27 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   27 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   28 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   28 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   28 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   31 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   31 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   32 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   32 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   32 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   32 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  142 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   33 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   33 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   33 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   34 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   34 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   34 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   35 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   35 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   35 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   35 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   36 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   36 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   37 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   37 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   39 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   39 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   39 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   40 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   40 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   40 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   40 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   42 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   42 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   42 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   42 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   43 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   43 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   43 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   43 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   43 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   44 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   44 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   49 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   49 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   51 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   51 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   51 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   51 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   54 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   54 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   54 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   54 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   54 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   54 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   47 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   47 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   47 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   47 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   55 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   58 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   58 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   59 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   59 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   60 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   60 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   61 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   61 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   64 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   64 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   64 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   65 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   65 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   65 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  134 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  134 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   69 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   69 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   69 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   69 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   69 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   70 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   70 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   70 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   73 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   73 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   73 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   73 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   74 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   74 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   75 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   75 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   75 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   75 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   76 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   76 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   76 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   77 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   77 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   77 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   77 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   79 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   79 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   79 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   84 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   84 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   85 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   85 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   85 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   85 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   86 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   86 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   86 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   86 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   87 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   87 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   87 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   88 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   88 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   88 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   90 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   90 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =   92 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   94 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   94 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   94 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   94 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =   95 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =   95 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   95 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =   95 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =   95 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   95 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   96 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   96 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   97 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   98 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   98 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   98 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  100 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  100 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  100 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  101 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  101 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  101 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =   50 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   50 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  102 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  102 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  103 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  103 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  104 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  104 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  105 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  105 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  105 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  106 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  106 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  106 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  109 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  109 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  109 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  109 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  110 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  110 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  111 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  111 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  111 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  112 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  112 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  113 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  113 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  114 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  114 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  115 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  115 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  115 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  115 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  118 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  122 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  122 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  122 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  122 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  123 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  123 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  123 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  124 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  124 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  124 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  124 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  124 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  124 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  126 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  126 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  126 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  126 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  133 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  133 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  133 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  133 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  133 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  135 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  135 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  137 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  137 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  137 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  137 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  138 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  138 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  138 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  141 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  141 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  141 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  143 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  143 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  145 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  145 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  145 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  145 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  145 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  145 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  146 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  146 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  146 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  149 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  150 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  150 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  150 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  151 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  151 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  152 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  152 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  152 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  156 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  156 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  157 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  157 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  157 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  157 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  158 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  158 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  158 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  161 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  161 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  163 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  163 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  163 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  163 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  163 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  164 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  164 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  165 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  165 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  165 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  165 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  165 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  167 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  168 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  168 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  168 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  170 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  170 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  170 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  170 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  121 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  121 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   46 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =   46 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =   46 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  172 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  172 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  172 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  172 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  173 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  173 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  173 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  174 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  174 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  174 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  174 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  180 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  182 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  182 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  183 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  183 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  183 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  183 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  184 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  184 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  185 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  185 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  185 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  185 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  187 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  187 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  187 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  187 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  188 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  188 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  188 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  188 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  188 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  188 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  189 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  189 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  189 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  189 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  189 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  189 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  190 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  190 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  190 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  193 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  194 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  194 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  194 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  194 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  195 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  195 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  196 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  196 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  196 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  196 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  177 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  177 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  177 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  198 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  198 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  198 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  198 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  198 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  199 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  199 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  200 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  200 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  200 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  201 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  201 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  201 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  201 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  201 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  201 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  203 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  203 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  203 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  203 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  203 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  205 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  205 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  205 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  206 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  206 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  206 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  207 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  208 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  208 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  208 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  208 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  211 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  211 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  211 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  211 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  213 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  217 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  217 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  218 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  218 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  219 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  219 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  219 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  219 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  220 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 26 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 27 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 55 )
      OR ( Nation_fk =  221 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  223 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  223 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  223 AND Religion_Group_fk = 28 )
      OR ( Nation_fk =  223 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  224 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  224 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  225 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  225 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  225 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  226 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  226 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  227 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  227 AND Religion_Group_fk = 57 )
      OR ( Nation_fk =  231 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  232 AND Religion_Group_fk = 51 )
      OR ( Nation_fk =  232 AND Religion_Group_fk = 53 )
      OR ( Nation_fk =  232 AND Religion_Group_fk = 23 )
      OR ( Nation_fk =  232 AND Religion_Group_fk = 57 )
     )

-----------------------------------------------------------------------------------------------------------
-- check results:
SELECT 
       distinct
           Field_fk
        ,  Sex_fk
        ,  Age_fk
        ,  Display
  FROM
             [forum].[dbo].[Pew_Nation_Religion_Age_Sex_Value]
WHERE
           Display = 0

ORDER BY
           Field_fk
        ,  Sex_fk
        ,  Age_fk

/*********************************************************************************************************/
