select distinct TABLE_NAME
                                      FROM INFORMATION_SCHEMA.COLUMNS
where 
TABLE_NAME

is not IN
(
Pew_G_20_3_Summary
Pew_GRFsite_URLs_Topic
Pew_Index_Cut_Points
Pew_Language
Pew_Lists
Pew_Locality
Pew_Locality_Answer
Pew_Locality_Value
Pew_Medians_byCtry_and_Religion
Pew_Migration
Pew_Migration_Data
Pew_Migration_Data_Quality_Level
Pew_Migration_Data_Source
Pew_Nation
Pew_Nation_Age_Sex_Value
Pew_Nation_Answer
Pew_Nation_Language
Pew_Nation_Religion_Age_Sex_Value
Pew_Nation_Religion_Answer
Pew_Nation_Religion_Fertility_Value
Pew_Nation_Religion_Value
Pew_Nation_Restriction_AVG
Pew_Nation_Subreligion_Distribution
Pew_Nation_Value
Pew_Preferred_Scenario
Pew_Question
Pew_Question_Displayable
Pew_Question_NoStd
Pew_Question_Std
Pew_Question_Topic
Pew_RDI
Pew_RDI_SubR
Pew_Religion_Group
Pew_Religion_Restriction_Top_Line
Pew_Sex
Pew_Survey_Answer
Pew_Survey_Tables_Displayable
Pew_Topic
Province
Restrictions_byCtry
RIndexes
Survey
Survey_data
Survey_locality
Survey_religion_code
sysdiagrams
temp_dscptn_view
temp_text_view
v_african_survey
v_Data_for_WRD_Religion_Comparison
v_GRI_20_01_all
v_pew_g_20_3_summary_2007
v_pew_g_20_3_summary_2008
v_pew_g_20_3_summary_2009
v_pew_g_20_3_summary_2010
v_pew_nation_religion_restriction_aggre_2007
v_pew_nation_religion_restriction_aggre_2008
v_pew_nation_religion_restriction_aggre_2009
v_pew_nation_religion_restriction_aggre_2010
v_pew_nation_religion_restriction_aggregation
V_Pew_Nation_Religion_Restriction_T_2006_2008
V_Pew_Nation_Religion_Restriction_T_2007_2009
V_Pew_Nation_Religion_Restriction_T_2008_2010
V_Pew_Nation_Restriction_AVG_2006_2008
V_Pew_Nation_Restriction_AVG_2007_2009
V_Pew_Nation_Restriction_AVG_2008_2010
V_Pew_Nation_Restriction_T_2006_2008
V_Pew_Nation_Restriction_T_2007_2009
V_Pew_Nation_Restriction_T_2008_2010
v_Pew_Religion_Composition
V_Pew_Religion_Restriction_Top_Line
v_pew_violence_locality
zg_WRD_Religion